apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: <your-registry>/flask-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "localhost"  # Use "localhost" as the Redis host since both containers are in the same pod.
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
